# Generated by Django 3.0.3 on 2020-06-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0004_auto_20200603_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_slug',
        ),
    ]
